(table as table ) as table =>
let
    #"Removed Columns" = if(Table.HasColumns(table,{"Column2"})) then Table.RemoveColumns(table,{"Column2"}) else table,
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Removed Columns", "Column1", {"id", "title", "avatarUrl", "accessType", "archived", "guestRoleId", "defaultProjectWorkflowId", "defaultTaskWorkflowId","members"}, {"id", "title", "avatarUrl", "accessType", "archived", "guestRoleId", "defaultProjectWorkflowId", "defaultTaskWorkflowId","members"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"id", type text}, {"title", type text}, {"avatarUrl", type text}, {"accessType", type text}, {"archived", type logical}, {"guestRoleId", type text}, {"defaultProjectWorkflowId", type text}, {"defaultTaskWorkflowId", type text}})
 in
   #"Changed Type"