(table as table ) as table => 
let
    #"Removed Columns" = if(Table.HasColumns(table,{"Column2"})) then Table.RemoveColumns(table,{"Column2"}) else table,
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Removed Columns", "Column1", {"id", "accountId", "title", "memberIds", "childIds", "parentIds", "avatarUrl", "myTeam"}, {"id", "accountId", "title", "memberIds", "childIds", "parentIds", "avatarUrl", "myTeam"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"id", type text}, {"accountId", type text}, {"title", type text}, {"avatarUrl", type text}, {"myTeam", type logical}})
in
    #"Changed Type"