(table as table ) as table =>
let
    #"Removed Columns" = if(Table.HasColumns(table,{"Column2"})) then Table.RemoveColumns(table,{"Column2"}) else table,
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Removed Columns", "Column1", {"taskId", "authorId", "title", "description", "updatedDate", "decisions", "attachmentIds", "type", "autoFinishOnApprove", "autoFinishOnReject", "finished", "id", "status", "folderId", "dueDate"}, {"taskId", "authorId", "title", "description", "updatedDate", "decisions", "attachmentIds", "type", "autoFinishOnApprove", "autoFinishOnReject", "finished", "id", "status", "folderId", "dueDate"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"taskId", type text}, {"authorId", type text}, {"title", type text}, {"description", type text}, {"updatedDate", type datetime}, {"type", type text}, {"autoFinishOnApprove", type logical}, {"autoFinishOnReject", type logical}, {"finished", type logical}, {"id", type text}, {"status", type text}, {"folderId", type text}, {"dueDate", type date}})
in
    #"Changed Type"