(table as table ) as table =>
let
    #"Removed Columns" = if(Table.HasColumns(table,{"Column2"})) then Table.RemoveColumns(table,{"Column2"}) else table,
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Removed Columns", "Column1", {"id", "authorId", "name", "createdDate", "version", "type", "contentType", "size", "taskId", "width", "height"}, {"id", "authorId", "name", "createdDate", "version", "type", "contentType", "size", "taskId", "width", "height"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"id", type text}, {"authorId", type text}, {"name", type text}, {"createdDate", type datetime}, {"version", type number}, {"type", type text}, {"contentType", type text}, {"size", type number}, {"taskId", type text}, {"width", Int64.Type}, {"height", Int64.Type}})
in
    #"Changed Type"